export const personnelItems = [
	{
		value: "employees.roles.ceo",
		label: "CEO",
		defaultValue: 0,
		minValue: 0,
		maxValue: 100000,
		step: 10,
	},
	{
		value: "employees.roles.cto",
		label: "CTO",
		defaultValue: 0,
		minValue: 0,
		maxValue: 80000,
		step: 10,
	},
	{
		value: "employees.roles.senior-dev",
		label: "Senior Developer",
		defaultValue: 0,
		minValue: 0,
		maxValue: 30000,
		step: 500,
	},
	{
		value: "employees.roles.mid-dev",
		label: "Mid-level Developer",
		defaultValue: 8000,
		minValue: 0,
		maxValue: 18000,
		step: 500,
	},
	{
		value: "employees.roles.junior-dev",
		label: "Junior Developer",
		defaultValue: 5000,
		minValue: 0,
		maxValue: 12000,
		step: 250,
	},
	{
		value: "employees.roles.designer",
		label: "UI/UX Designer",
		defaultValue: 7000,
		minValue: 0,
		maxValue: 15000,
		step: 500,
	},
	{
		value: "employees.roles.product-manager",
		label: "Product Manager",
		defaultValue: 11000,
		minValue: 0,
		maxValue: 25000,
		step: 500,
	},
	{
		value: "employees.roles.qa-engineer",
		label: "QA Engineer",
		defaultValue: 6000,
		minValue: 0,
		maxValue: 16000,
		step: 250,
	},
];

/* export const operationsItems = [
	{
		value: "items.rent",
		label: "Office Rent",
		defaultValue: 8000,
		minValue: 0,
		maxValue: 25000,
		step: 500,
	},
	{
		value: "items.utilities",
		label: "Utilities",
		defaultValue: 1200,
		minValue: 0,
		maxValue: 5000,
		step: 100,
	},
	{
		value: "items.insurance",
		label: "Insurance",
		defaultValue: 800,
		minValue: 0,
		maxValue: 3000,
		step: 100,
	},
	{
		value: "items.cleaning",
		label: "Cleaning Services",
		defaultValue: 600,
		minValue: 0,
		maxValue: 2000,
		step: 100,
	},
	{
		value: "items.security",
		label: "Security",
		defaultValue: 1000,
		minValue: 0,
		maxValue: 3000,
		step: 100,
	},
	{
		value: "items.maintenance",
		label: "Maintenance",
		defaultValue: 800,
		minValue: 0,
		maxValue: 2500,
		step: 100,
	},
]; */

export const marketingItems = [
	{
		value: "items.digital-ads",
		label: "Digital Advertising",
		defaultValue: 15000,
		minValue: 0,
		maxValue: 100000,
		step: 1000,
	},
	{
		value: "items.content",
		label: "Content Marketing",
		defaultValue: 5000,
		minValue: 0,
		maxValue: 25000,
		step: 500,
	},
	{
		value: "items.seo",
		label: "SEO Services",
		defaultValue: 3000,
		minValue: 0,
		maxValue: 15000,
		step: 500,
	},
	{
		value: "items.social-media",
		label: "Social Media Management",
		defaultValue: 2500,
		minValue: 0,
		maxValue: 10000,
		step: 250,
	},
	{
		value: "items.events",
		label: "Events & Conferences",
		defaultValue: 8000,
		minValue: 0,
		maxValue: 50000,
		step: 1000,
	},
	{
		value: "items.pr",
		label: "Public Relations",
		defaultValue: 4000,
		minValue: 0,
		maxValue: 15000,
		step: 500,
	},
];

export const technologyItems = [
	{
		value: "items.software",
		label: "Software Licenses",
		defaultValue: 2500,
		minValue: 0,
		maxValue: 15000,
		step: 250,
	},
	{
		value: "items.infrastructure",
		label: "Cloud Infrastructure",
		defaultValue: 3500,
		minValue: 0,
		maxValue: 20000,
		step: 500,
	},
	{
		value: "items.tools",
		label: "Development Tools",
		defaultValue: 1500,
		minValue: 0,
		maxValue: 8000,
		step: 200,
	},
	{
		value: "items.security",
		label: "Security Tools",
		defaultValue: 1200,
		minValue: 0,
		maxValue: 5000,
		step: 200,
	},
	{
		value: "items.analytics",
		label: "Analytics & Monitoring",
		defaultValue: 800,
		minValue: 0,
		maxValue: 3000,
		step: 100,
	},
	{
		value: "items.backup",
		label: "Backup & Recovery",
		defaultValue: 600,
		minValue: 0,
		maxValue: 2000,
		step: 100,
	},
];

export const STANDARD_CATEGORY_CONFIGS = {
	/* personnel: {
		key: "personnel",
		label: "Personnel",
		title: "Personnel Costs",
		description: "Team salaries, roles, and contractors",
		iconName: "Users",
		defaultItems: '',
		createInitialData: () => ({
			employees: { roles: {} },
			contractors: { enabled: false, types: {} },
		}),
	},
	operations: {
		key: "operations",
		label: "Operations",
		title: "Operations & Facilities",
		description: "Office, facilities, and operational expenses",
		iconName: "Building",
		defaultItems: operationsItems,
		createInitialData: () => ({ items: {} }),
	},
	marketing: {
		key: "marketing",
		label: "Marketing",
		title: "Marketing & Sales",
		description: "Acquisition, content, and growth programs",
		iconName: "Megaphone",
		defaultItems: marketingItems,
		createInitialData: () => ({ items: {} }),
	},
	technology: {
		key: "technology",
		label: "Technology",
		title: "Technology & Infrastructure",
		description: "Software, infrastructure, and tooling",
		iconName: "Server",
		defaultItems: technologyItems,
		createInitialData: () => ({ items: {} }),
	}, */
};

export const createDefaultCostStructure = () => ({
	customCategories: null,
});
